apiVersion: v1
kind: Service
metadata:
  name: robots-java
spec:
  type: NodePort
  ports:
    - name: server
      nodePort: 32001
      port: 8080
      targetPort: 8081
    - name: management
      nodePort: 32002
      port: 8081
      targetPort: 8081
  selector:
    app: robots-java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: robots-java
  name: robots-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robots-java
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: robots-java
    spec:
      containers:
      - image: core.harbor.cz.shenlan.com/rv-owl-uat/robots:78
        name: robots-java-uat
        resources: {}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "uat"
      imagePullSecrets:
      - name: regcred
status: {}
