apiVersion: v1
kind: Service
metadata:
  name: owl-service
spec:
  type: NodePort
  ports:
    - name: server
      nodePort: 31001
      port: 8080
      targetPort: 8201
    - name: management
      nodePort: 31002
      port: 8081
      targetPort: 8201
  selector:
    app: owl-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: owl-service
  name: owl-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owl-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: owl-service
    spec:
      containers:
      - image: core.harbor.cz.shenlan.com/rv-owl-uat/owl-service-uat:78
        name: owl-service-uat
        resources: {}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "uat"
      imagePullSecrets:
      - name: regcred
status: {}
