apiVersion: v1
kind: Service
metadata:
  name: owl-business
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8206
      nodePort: 31006
  selector:
    app: owl-business
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: owl-business
  name: owl-business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owl-business
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: owl-business
    spec:
      containers:
      - image: core.harbor.cz.shenlan.com/rv-owl-uat/owl-business-uat:77
        name: owl-business-uat
        resources: {}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "uat"
      imagePullSecrets:
      - name: regcred
status: {}
